version: "3.8"

services:

  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
    environment:
      MYSQL_TCP_PORT: 3306
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - "3306:3306"
    networks:
      - inception-networks

  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
    volumes:
      - wordpress_data:/var/www/html/wordpress
    environment:
      MYSQL_TCP_PORT: 3306
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    networks:
      - inception-networks
  nginx:
    container_name: nginx_v1
    build:
      context: requirements/nginx
    volumes:
      - wordpress_data:/var/www/html/wordpress
    ports:
      - 443:443
    depends_on:
      - wordpress
    networks:
      - inception-networks

networks:
  inception-networks:
    driver: bridge
    name: inception-networks

volumes:
  wordpress_data: