version: "3.8"

services:

  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
    restart: on-failure
    env_file:
      - path: .env

    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception-networks

  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
    restart: on-failure
    volumes:
      - wordpress_data:/var/www/html/wordpress
    env_file:
      - path: .env
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    networks:
      - inception-networks
    
  nginx:
    container_name: nginx_v1
    build:
      context: requirements/nginx
    restart: on-failure
    volumes:
      - wordpress_data:/var/www/html/wordpress
    ports:
      - 443:443
    depends_on:
      - wordpress
    networks:
      - inception-networks

networks:
  inception-networks:

volumes:
  mariadb_data:
    name: "mariadb_data"
    driver_opts:
      type: none
      o: bind
      device: "$HOME/data/mariadb_data"
  wordpress_data:
    name: "wordpress_data"

    driver_opts:
      type: none
      o: bind
      device: "$HOME/data/wordpress_data"