version: "3.8"

services:
  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile      
    ports:
      - 443:443
      - 80:80
    restart: always
    volumes:
      - /home/esalim/Inception/srcs/requirements/nginx/conf/conf.d:/etc/nginx/conf.d
      - /home/esalim/Inception/srcs/requirements/nginx/conf/sites-enabled:/etc/nginx/sites-enabled
    